### ISSUE TITLE
"usage" command terminates shell session

### ISSUE THREAD

**Issue by blitz** [nixbuild/feedback#1]
**Observation**:

When connecting using `ssh -T eu.nixbuild.net shell` entering `usage` will abort the shell session without result.

**Expected Result**:

Command shows usage information.

**Comment by blitz** [comment]
`show drv` has the same behavior.

**Comment by rickynils** [comment]
@blitz There was a temporary database issue around the time you reported this issue, I'd say it is very likely that was the reason for the erroneous shell behavior. The issue is no longer reproducible.
