### ISSUE TITLE
api for getting monthly CPU hours used

### ISSUE THREAD

**Issue by cdepillabout** [nixbuild/feedback#11]
Hi, I'd like to be able to easily monitor the number of build hours we've used so far.

I'm thinking about creating an AWS Lambda job that runs like once an hour or so, scrapes nixbuild.net's SSH [`usage`](https://docs.nixbuild.net/configuration/#account-usage) output, and uploads the results to AWS CloudWatch.  And then potentially create a CloudWatch alarm that would alert when we go over some set amount of hours.

Although I'm wondering if you have an HTTP API for querying things like CPU hours used.  I imagine that might be slightly easier for us to use.  Or alternatively if there is any other way you'd suggest for getting usage information into a monitoring solution like CloudWatch.

**Comment by rickynils** [comment]
Thank you for reporting this. We are working on an HTTP API, and we'll make sure to add a way to retrieve the information you've requested.

**Comment by cdepillabout** [comment]
Great, thanks a lot  :-)

**Comment by rickynils** [comment]
We launched the API now: https://docs.nixbuild.net/api-usage/

There is a `/usage` endpoint that returns the number of CPU seconds spent during a specific period (selectable with `from` and `to` params). There are also endpoint for getting detailed info on builds. Check out the [API reference](https://docs.nixbuild.net/api).

**Comment by cdepillabout** [comment]
Oh nice, this will be very helpful!

**Comment by rickynils** [comment]
@cdepillabout If you have any other API requests, feel free submitting more issues.
