### ISSUE TITLE
Clients of remote store builds sometimes hang when finished

### ISSUE THREAD

**Issue by michaelpj** [nixbuild/feedback#24]
Running my usual workflow: https://github.com/input-output-hk/cardano-haskell-packages/actions/runs/4500842002/jobs/7922637054?pr=163

I believe it's completed: `builds list -r` shows nothing running, and the top of `builds list` shows the target derivation as `[Built]`. But the Nix command has not terminated. It appears to just be sitting there indefinitely. I don't know what it's waiting for.

**Comment by rickynils** [comment]
Have you seen this issue several times?

**Comment by michaelpj** [comment]
I saw it a couple of times, including when building locally with remote stores, but not recently. Then again, I haven't been experimenting as much recently. We can probably close and I'll reopen if it happens again.
