### ISSUE TITLE
Possible typos in "Running Remote Builds" page

### ISSUE THREAD

**Issue by cpick** [nixbuild/feedback#34]
The [Running Remote Builds](https://docs.nixbuild.net/remote-builds/) page looks like it might have a few typos:
1. "and what derivations **that** must" likely should have "derivations must".
1. "uploaed" likely should be "uploaded".
1. "closures in your local store that **was** never" likely should have "that were never". 
1. "run as the same user that **own** /nix" likely should have "owns".
1. "which **makes** building in a remote store not possible if the evaluation store **also is** remote" likely should have "make" and "is also".

I'm not great at grammar so please take these suggestions with a grain of salt.
Thanks for running such a useful service and providing comprehensive documentation!

**Comment by rickynils** [comment]
Thank you for finding these mistakes!

**Comment by rickynils** [comment]
Deployed fixes.
