### ISSUE TITLE
slow builds?

### ISSUE THREAD

**Issue by LovingMelody** [nixbuild/feedback#40]
Noticed that build times for nixbuild has become quite slower than just building using gitihub actions. wine staging v9.20 took about 1h35min on github actions but over 2h with 4 cpus and the build was still not completed using nixbuild.

**Comment by rickynils** [comment]
@LovingMelody Do you have the build id of that build? I can't seem to find any build of wine 9.20, but maybe I'm looking for the wrong package names.

**Comment by LovingMelody** [comment]
> @LovingMelody Do you have the build id of that build? I can't seem to find any build of wine 9.20, but maybe I'm looking for the wrong package names.

3369529

**Comment by rickynils** [comment]
@LovingMelody Sorry, I found the build now. It looks like it ran for 1h27m on nixbuild.net before it ran out of memory and was restarted. The new build was then cancelled by the user.

The last log line of the build that ran out of memory was this:

```
STRIPPROG=x86_64-w64-mingw32-strip /build/wine-9.20/tools/install-sh -m 644  programs/wineconsole/x86_64-windows/wineconsole.exe /nix/store/bryr5c7qb491phq2cjs1cwmvx47vwlgl-wine-wow-staging-9.20/lib/wine/x86_64-windows/wineconsole.exe
```

That looks like it could be something at the end of the build, so maybe the time is in line with the github action?

**Comment by rickynils** [comment]
@LovingMelody It looks like 3369529 is the cancelled build, and 3369048 is the original build that ran out of memory.

**Comment by LovingMelody** [comment]
That explains the build time then, thanks for looking into it.
