### ISSUE TITLE
Remote store builds (--store) don't work with `nix-build`, only `nix build`

### ISSUE THREAD

**Issue by rickynils** [nixbuild/feedback#5]
If you try `nix-build --eval-store auto --store ssh-ng://eu.nixbuild.net ...` (note `nix-build` instead of `nix build`) you get an error because `WopQueryMissing`.

Apparently `nix-build` uses the daemon RPC slightly different than `nix build`.

**Comment by rickynils** [comment]
This has been fixed and deployed.

**Comment by cpick** [comment]
This is still listed as a limitation in [the documentation](https://docs.nixbuild.net/remote-builds/#limitations-of-remote-store-builds-in-nixbuildnet), but I assume that's out of date since this issue is now closed?
